steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/apib:latest', '-f', './apib/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "asia.gcr.io/$PROJECT_ID/apib:latest"]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - container
  - clusters
  - get-credentials
  - $_TARGET_CLUSTER
  - --zone=$_ZONE
  - --project=$PROJECT_ID
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'delete'
  - 'pod'
  - -l
  - app.kubernetes.io/instance=$_TARGET_LABEL