apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apib
  labels:
    app.kubernetes.io/name: {{ include "payment-apib.name" . }}
    helm.sh/chart: {{ include "payment-apib.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "apib-ip"
spec:
  rules:
  - http:
      paths:
      - path: /payment
        backend:
          serviceName: payment-apib
          servicePort: 3000
