# Default values for payment-apib.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
projectID: jphack2018-219415

image:
  repository: payment-apib
  tag: latest
  pullPolicy: Always
  containerPort: 3000

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3000

ingress:
  enabled: true
  annotations: {}
  path: /payment

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
